/*
 * Cross-checks the Kotlin Omron protocol port against vectors generated by the
 * Python reference (src/polar_ble/omron_evolv.py). If these pass, the Kotlin
 * frame builders / parsers are byte-for-byte equivalent.
 */

package com.polarppgbp.omron

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class OmronProtocolTest {

    private fun hex(b: ByteArray) = OmronProtocol.bytesToHex(b)

    @Test
    fun constantFramesMatchPython() {
        assertEquals("0800000000100018", hex(OmronProtocol.START_TRANSMISSION))
        assertEquals("080f000000000007", hex(OmronProtocol.END_TRANSMISSION))
    }

    @Test
    fun readEepromFramesMatchPython() {
        assertEquals("08010002ac38009f", hex(OmronProtocol.buildReadEeprom(0x02AC, 0x38)))
        assertEquals("0801000260080063", hex(OmronProtocol.buildReadEeprom(0x0260, 8)))
    }

    @Test
    fun writeEepromFrameMatchesPython() {
        val frame = OmronProtocol.buildWriteEeprom(0x0286, OmronProtocol.hexToBytes("1122334455667788"))
        assertEquals("1001c0028608112233445566778800d5", hex(frame))
    }

    @Test
    fun crcOfValidPacketIsZero() {
        val pkt = OmronProtocol.hexToBytes("0c810002ac04010203040023")
        assertEquals(0, OmronProtocol.xorCrc(pkt))
    }

    @Test
    fun parseRecordMatchesPython() {
        val rec = OmronProtocol.parseRecord(OmronProtocol.hexToBytes("505f1a4859cb078f000000000000"))!!
        assertEquals(120, rec.sysMmHg)
        assertEquals(80, rec.diaMmHg)
        assertEquals(72, rec.pulseBpm)
        assertEquals("2026-06-14T11:30:15", rec.takenAtIso())
        assertTrue(rec.irregularHeartbeat)
        assertTrue(!rec.bodyMovement)
    }

    @Test
    fun blankRecordIsNull() {
        assertNull(OmronProtocol.parseRecord(ByteArray(14) { 0xFF.toByte() }))
    }

    @Test
    fun parseInboundReadResponse() {
        val pkt = OmronProtocol.parseInbound(OmronProtocol.hexToBytes("0c810002ac04010203040023"))
        assertEquals("8100", hex(pkt.packetType))
        assertEquals(0x02AC, pkt.eepromAddress)
        assertEquals("01020304", hex(pkt.data))
    }

    @Test
    fun channelsNeededSplitsCorrectly() {
        assertEquals(1, OmronProtocol.channelsNeeded(8))
        assertEquals(1, OmronProtocol.channelsNeeded(16))
        assertEquals(2, OmronProtocol.channelsNeeded(17))
        assertEquals(4, OmronProtocol.channelsNeeded(64))
    }

    @Test
    fun planReadsWholeRegionByDefault() {
        val reads = OmronProtocol.planRecordReads()
        assertEquals(1, reads.size)
        assertEquals(OmronProtocol.USER_RECORDS_ADDR, reads[0].address)
        assertEquals(100 * 14, reads[0].size)
    }

    @Test
    fun planReadsUnreadNoWrap() {
        val reads = OmronProtocol.planRecordReads(onlyUnread = true, lastWrittenSlot = 10, unreadCount = 3)
        assertEquals(1, reads.size)
        assertEquals(OmronProtocol.USER_RECORDS_ADDR + 7 * 14, reads[0].address)
        assertEquals(3 * 14, reads[0].size)
    }

    @Test
    fun planReadsUnreadWrapped() {
        // lastSlot < unread => wrap: tail (older) then head (recent).
        val reads = OmronProtocol.planRecordReads(onlyUnread = true, lastWrittenSlot = 2, unreadCount = 5)
        assertEquals(2, reads.size)
        // tail = last (5-2=3) slots of the buffer
        assertEquals(OmronProtocol.USER_RECORDS_ADDR + (100 - 3) * 14, reads[0].address)
        assertEquals(3 * 14, reads[0].size)
        // head = first 2 slots
        assertEquals(OmronProtocol.USER_RECORDS_ADDR, reads[1].address)
        assertEquals(2 * 14, reads[1].size)
    }
}
