/*
 * Cross-checks the Kotlin Omron protocol port against vectors generated by the
 * Python reference (src/polar_ble/omron_evolv.py). If these pass, the Kotlin
 * frame builders / parsers are byte-for-byte equivalent.
 */

package com.polarppgbp.omron

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

class OmronProtocolTest {

    private fun hex(b: ByteArray) = OmronProtocol.bytesToHex(b)

    @Test
    fun constantFramesMatchPython() {
        assertEquals("0800000000100018", hex(OmronProtocol.START_TRANSMISSION))
        assertEquals("080f000000000007", hex(OmronProtocol.END_TRANSMISSION))
    }

    @Test
    fun readEepromFramesMatchPython() {
        assertEquals("08010002ac38009f", hex(OmronProtocol.buildReadEeprom(0x02AC, 0x38)))
        assertEquals("0801000260080063", hex(OmronProtocol.buildReadEeprom(0x0260, 8)))
    }

    @Test
    fun writeEepromFrameMatchesPython() {
        val frame = OmronProtocol.buildWriteEeprom(0x0286, OmronProtocol.hexToBytes("1122334455667788"))
        assertEquals("1001c0028608112233445566778800d5", hex(frame))
    }

    @Test
    fun crcOfValidPacketIsZero() {
        val pkt = OmronProtocol.hexToBytes("0c810002ac04010203040023")
        assertEquals(0, OmronProtocol.xorCrc(pkt))
    }

    @Test
    fun parseRecordMatchesPython() {
        val rec = OmronProtocol.parseRecord(OmronProtocol.hexToBytes("505f1a4859cb078f000000000000"))!!
        assertEquals(120, rec.sysMmHg)
        assertEquals(80, rec.diaMmHg)
        assertEquals(72, rec.pulseBpm)
        assertEquals("2026-06-14T11:30:15", rec.takenAtIso())
        assertTrue(rec.irregularHeartbeat)
        assertTrue(!rec.bodyMovement)
    }

    @Test
    fun blankRecordIsNull() {
        assertNull(OmronProtocol.parseRecord(ByteArray(14) { 0xFF.toByte() }))
    }

    @Test
    fun parseInboundReadResponse() {
        val pkt = OmronProtocol.parseInbound(OmronProtocol.hexToBytes("0c810002ac04010203040023"))
        assertEquals("8100", hex(pkt.packetType))
        assertEquals(0x02AC, pkt.eepromAddress)
        assertEquals("01020304", hex(pkt.data))
    }

    @Test
    fun channelsNeededSplitsCorrectly() {
        assertEquals(1, OmronProtocol.channelsNeeded(8))
        assertEquals(1, OmronProtocol.channelsNeeded(16))
        assertEquals(2, OmronProtocol.channelsNeeded(17))
        assertEquals(4, OmronProtocol.channelsNeeded(64))
    }

    @Test
    fun planReadsWholeRegionByDefault() {
        val reads = OmronProtocol.planRecordReads()
        assertEquals(1, reads.size)
        assertEquals(OmronProtocol.USER_RECORDS_ADDR, reads[0].address)
        assertEquals(100 * 14, reads[0].size)
    }

    @Test
    fun planReadsUnreadNoWrap() {
        val reads = OmronProtocol.planRecordReads(onlyUnread = true, lastWrittenSlot = 10, unreadCount = 3)
        assertEquals(1, reads.size)
        assertEquals(OmronProtocol.USER_RECORDS_ADDR + 7 * 14, reads[0].address)
        assertEquals(3 * 14, reads[0].size)
    }

    @Test
    fun planReadsUnreadWrapped() {
        // lastSlot < unread => wrap: tail (older) then head (recent).
        val reads = OmronProtocol.planRecordReads(onlyUnread = true, lastWrittenSlot = 2, unreadCount = 5)
        assertEquals(2, reads.size)
        // tail = last (5-2=3) slots of the buffer
        assertEquals(OmronProtocol.USER_RECORDS_ADDR + (100 - 3) * 14, reads[0].address)
        assertEquals(3 * 14, reads[0].size)
        // head = first 2 slots
        assertEquals(OmronProtocol.USER_RECORDS_ADDR, reads[1].address)
        assertEquals(2 * 14, reads[1].size)
    }

    // ---- cuff clock (#9 / #18) ----
    //
    // Fixtures below are real bytes captured from BLEsmart_0000021F005FBFF75ABE on
    // 2026-07-26, including the halted-RTC state after a deliberate battery pull.
    // Do not "tidy" them.

    @Test
    fun clockParsesValidHardwareSample() {
        // phone clock read 19:39:24.6 when this was captured
        val c = OmronProtocol.parseTimeSync(OmronProtocol.hexToBytes("a0c0071a131a192711ee"))
        assertEquals(2026, c.year)
        assertEquals(7, c.month)
        assertEquals(26, c.day)
        assertEquals(19, c.hour)
        assertEquals(39, c.minute)
        assertEquals(25, c.second)
        assertTrue(c.checksumOk)
        assertFalse(c.halted)
        assertTrue(c.valid)
        assertEquals("2026-07-26T19:39:25", c.iso())
    }

    @Test
    fun clockAllFourHardwareSamplesChecksumOk() {
        listOf(
            "a0c0071a131a192711ee",
            "a0c0071a131a3a2aed12",
            "a0c0071a131a3533e916",
            "a0c0071a131a2a3aed12",
        ).forEach { h ->
            val c = OmronProtocol.parseTimeSync(OmronProtocol.hexToBytes(h))
            assertTrue("checksum should verify for $h", c.checksumOk)
            assertFalse("should not look halted: $h", c.halted)
        }
    }

    @Test
    fun clockDetectsHaltedSentinel() {
        // Captured 20:22 and again 20:28 after pulling the batteries: byte-identical,
        // seconds field 0x3F (63), checksum still valid.
        val c = OmronProtocol.parseTimeSync(OmronProtocol.hexToBytes("a0c0071a141a3f0011ee"))
        assertEquals(63, c.secondRaw)
        assertTrue("0x3F must be recognised as halted", c.halted)
        assertTrue("the device still checksums the sentinel", c.checksumOk)
        assertFalse("a halted clock is never valid", c.valid)
        assertEquals(59, c.second) // clipped for display only
    }

    @Test
    fun clockEncodeRoundTripsHardwareSample() {
        val e = OmronProtocol.encodeTimeSync(2026, 7, 26, 19, 39, 25)
        assertEquals("a0c0071a131a192711ee", OmronProtocol.bytesToHex(e))
    }

    @Test
    fun clockEncodedChecksumObeysBothRules() {
        val b = OmronProtocol.encodeTimeSync(2026, 12, 31, 23, 59, 59)
        var sum = 0
        for (i in 0 until 8) sum += b[i].toInt() and 0xFF
        sum = sum and 0xFF
        assertEquals("byte 9 is the low byte of the sum", sum, b[9].toInt() and 0xFF)
        assertEquals(
            "byte 8 + byte 9 == 0xFF",
            0xFF,
            ((b[8].toInt() and 0xFF) + (b[9].toInt() and 0xFF)) and 0xFF,
        )
    }

    @Test
    fun clockEncodeRejectsSentinelSeconds() {
        // Guards against ever writing the halted sentinel ourselves.
        assertThrows(IllegalArgumentException::class.java) {
            OmronProtocol.encodeTimeSync(2026, 7, 26, 20, 0, 63)
        }
    }

    @Test
    fun clockWriteGoesToSettingsWriteMirror() {
        assertEquals(OmronProtocol.SETTINGS_WRITE_ADDR + 0x14, OmronProtocol.timeSyncWriteAddress())
        assertEquals(0x029A, OmronProtocol.timeSyncWriteAddress())
    }

    @Test
    fun clockRoundTripOverManyTimes() {
        for (h in 0..23) for (m in listOf(0, 7, 31, 59)) {
            val e = OmronProtocol.encodeTimeSync(2026, 7, 26, h, m, 12)
            val c = OmronProtocol.parseTimeSync(e)
            assertTrue(c.checksumOk)
            assertTrue(c.valid)
            assertEquals(h, c.hour)
            assertEquals(m, c.minute)
            assertEquals(12, c.second)
            assertEquals(26, c.day)
            assertEquals(7, c.month)
            assertEquals(2026, c.year)
        }
    }
}
